$axure.loadCurrentPage({
  "url":"花市一点通.html",
  "generationDate":new Date(1516111770446.41),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"07c2d38e6c7241369b71da1840f3650d",
    "type":"Axure:Page",
    "name":"花市一点通",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"用例 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"wait",
                "description":"等待3000毫秒",
                "waitTime":3000},
{
                "action":"fadeWidget",
                "description":"隐藏 启动画面 淡入淡出 500 ms",
                "objectsToFades":[{
                    "objectPath":["4a1033564ec54a359d38568845cf29ba"],
                    "fadeInfo":{
                      "fadeType":"hide",
                      "options":{
                        "easing":"fade",
                        "duration":500,
                        "showType":"none"}}}]}]}]}},
    "diagram":{
      "objects":[{
          "id":"056fee0eb50a463bb8260f33e08798c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":670},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"040eb4c086c748a7a112988194d5c499",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":670},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/花市一点通/u0.png"}},
{
          "id":"eaa99c89a8a64c3582492957da9a6a34",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":22.5,
              "y":20},
            "size":{
              "width":147,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a9379ee03ca41f6a8bd18fc5d2e3ab2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":22.5,
                  "y":20},
                "size":{
                  "width":147,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/花市一点通/u2.jpg"}},
{
          "id":"463395f535014d38ae4b41f9056df201",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":190.5,
              "y":20},
            "size":{
              "width":147,
              "height":109},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec2ab7c074674ceb82de26eddf6033db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190.5,
                  "y":20},
                "size":{
                  "width":147,
                  "height":109},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/花市一点通/u4.png"}},
{
          "id":"6bd9f42ac7554955ae59629633304fc7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":30.5,
              "y":28},
            "size":{
              "width":131,
              "height":95},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6ea4747003a4adea4b91b3203a9de9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":30.5,
                  "y":28},
                "size":{
                  "width":131,
                  "height":95},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/花市一点通/u6.png"}},
{
          "id":"2a38bb876b3b4c5f9b5cf2199896a302",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'幼圆 Bold', '幼圆'",
            "fontSize":"12px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":36,
              "y":106},
            "size":{
              "width":53,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6802caa209f244f7afae31a44586d2aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'幼圆 Bold', '幼圆'",
                "fontSize":"12px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":36,
                  "y":106},
                "size":{
                  "width":53,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"534c38e6c3684e9881bc9987519d8177",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":198.5,
              "y":27},
            "size":{
              "width":131,
              "height":95},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be7bc044e9ba485faf89d12bbdace9cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":198.5,
                  "y":27},
                "size":{
                  "width":131,
                  "height":95},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/花市一点通/u6.png"}},
{
          "id":"1b2e02400c274897a35cd7e0c09e9bd1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'幼圆 Bold', '幼圆'",
            "fontSize":"12px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":204,
              "y":105},
            "size":{
              "width":53,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b27b2a0b0a8941b79ca5ddeb4708d8e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'幼圆 Bold', '幼圆'",
                "fontSize":"12px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":204,
                  "y":105},
                "size":{
                  "width":53,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"08be0606f21f4dfc8f7c1cf2b812663f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":22.5,
              "y":149},
            "size":{
              "width":147,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44513f76fd074854bf2fee4bf5d52274",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":22.5,
                  "y":149},
                "size":{
                  "width":147,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/花市一点通/u14.jpg"}},
{
          "id":"7a3086c1ae894f25ba32a1743fae9872",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":190.5,
              "y":149},
            "size":{
              "width":147,
              "height":109},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"084171618f1c40e480a148469ea122bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190.5,
                  "y":149},
                "size":{
                  "width":147,
                  "height":109},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/花市一点通/u16.jpg"}},
{
          "id":"21d2f267fdf643a4a761d7280c4009b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":30.5,
              "y":157},
            "size":{
              "width":131,
              "height":95},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da18cc6f05ea4c8ca7b04307ad503529",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":30.5,
                  "y":157},
                "size":{
                  "width":131,
                  "height":95},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/花市一点通/u6.png"}},
{
          "id":"87cc9cacd5b5424487951a77764bade7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'幼圆 Bold', '幼圆'",
            "fontSize":"12px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":36,
              "y":235},
            "size":{
              "width":53,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81cdd2d4cd2a4c61a52541b58c39937e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'幼圆 Bold', '幼圆'",
                "fontSize":"12px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":36,
                  "y":235},
                "size":{
                  "width":53,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"836838fdaaa44bfeb71beb664ea3ca72",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":198.5,
              "y":156},
            "size":{
              "width":131,
              "height":95},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69ea2faf54374e30a4fc8caba44701b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":198.5,
                  "y":156},
                "size":{
                  "width":131,
                  "height":95},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/花市一点通/u6.png"}},
{
          "id":"46071d1dc25349a3984b662773d0f584",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'幼圆 Bold', '幼圆'",
            "fontSize":"12px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":204,
              "y":234},
            "size":{
              "width":66,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"569db57dfe2f40bf8577f3579c70c05a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'幼圆 Bold', '幼圆'",
                "fontSize":"12px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":204,
                  "y":234},
                "size":{
                  "width":66,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"022498a4fd9a46dd880bc77886dae5d1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":22.5,
              "y":278},
            "size":{
              "width":147,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4ab49ee606a4c599afb1cca95ccd513",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":22.5,
                  "y":278},
                "size":{
                  "width":147,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/花市一点通/u26.jpg"}},
{
          "id":"04a131afd2ca4a78a42b4fcb03643521",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":190.5,
              "y":278},
            "size":{
              "width":147,
              "height":109},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b04b61858c224c5c8015f9e5fdb959eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190.5,
                  "y":278},
                "size":{
                  "width":147,
                  "height":109},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/花市一点通/u28.jpg"}},
{
          "id":"8a4f75e3ac084b88a58fd3550bf959df",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":30.5,
              "y":286},
            "size":{
              "width":131,
              "height":95},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfa4b0dce0fc44fda2abe8daad664002",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":30.5,
                  "y":286},
                "size":{
                  "width":131,
                  "height":95},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/花市一点通/u6.png"}},
{
          "id":"9836f1fdf21b4b0ebf184671f40eab2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'幼圆 Bold', '幼圆'",
            "fontSize":"12px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":36,
              "y":364},
            "size":{
              "width":53,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7af20f05283442d79bc4c2d5fd2a34ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'幼圆 Bold', '幼圆'",
                "fontSize":"12px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":36,
                  "y":364},
                "size":{
                  "width":53,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab9b47655dc144e18a9e5fb4cc1ab107",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":198.5,
              "y":285},
            "size":{
              "width":131,
              "height":95},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06fa125962ef4be08fa7edbf5abb05f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":198.5,
                  "y":285},
                "size":{
                  "width":131,
                  "height":95},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/花市一点通/u6.png"}},
{
          "id":"0c542348152643208308b6db33d8e530",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'幼圆 Bold', '幼圆'",
            "fontSize":"12px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":204,
              "y":363},
            "size":{
              "width":53,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45f79a07b8aa4ff1a5078e730a45d593",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'幼圆 Bold', '幼圆'",
                "fontSize":"12px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":204,
                  "y":363},
                "size":{
                  "width":53,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d28d0d858cb5471dab361e155747067d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":22.5,
              "y":410},
            "size":{
              "width":147,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d6c6cec28c04b93ba5bc735f428847a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":22.5,
                  "y":410},
                "size":{
                  "width":147,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/花市一点通/u38.jpg"}},
{
          "id":"a2080f87b8d64ee28f106c8a20a9bfea",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":190.5,
              "y":410},
            "size":{
              "width":147,
              "height":109},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60237bf28a3440fe9bed8e6851f4c458",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190.5,
                  "y":410},
                "size":{
                  "width":147,
                  "height":109},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/花市一点通/u40.jpg"}},
{
          "id":"3a6e1318340b4d95a3a3e9f4c1e1dc2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":30.5,
              "y":418},
            "size":{
              "width":131,
              "height":95},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87ac0a6b7a77486e87b05b2e94ffc1f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":30.5,
                  "y":418},
                "size":{
                  "width":131,
                  "height":95},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/花市一点通/u6.png"}},
{
          "id":"493b942a9a50422392c97b58961b37fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'幼圆 Bold', '幼圆'",
            "fontSize":"12px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":36,
              "y":496},
            "size":{
              "width":92,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdbb0dfed5814cb2b99f99d135d661b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'幼圆 Bold', '幼圆'",
                "fontSize":"12px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":36,
                  "y":496},
                "size":{
                  "width":92,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"07b90d0dc8c14611be43431922feefc9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":198.5,
              "y":418},
            "size":{
              "width":131,
              "height":95},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc472651d65f4a6ca60f5ab21c887cab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":198.5,
                  "y":418},
                "size":{
                  "width":131,
                  "height":95},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/花市一点通/u6.png"}},
{
          "id":"93b5d9f636714318ae054583d59f9c7d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'幼圆 Bold', '幼圆'",
            "fontSize":"12px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":204,
              "y":496},
            "size":{
              "width":53,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5ce4804bf8d4858af9510c27b4d3456",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'幼圆 Bold', '幼圆'",
                "fontSize":"12px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":204,
                  "y":496},
                "size":{
                  "width":53,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"45307a7af6544025b34e192cb8559944",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":22.5,
              "y":540},
            "size":{
              "width":147,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3a2ff857c684802a595d1995851f8ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":22.5,
                  "y":540},
                "size":{
                  "width":147,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/花市一点通/u50.jpg"}},
{
          "id":"9b4911a42bb04c12b767fb0ff0313450",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":190.5,
              "y":540},
            "size":{
              "width":147,
              "height":109},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d80cd1625e294ec7b13b9487c25ca09e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190.5,
                  "y":540},
                "size":{
                  "width":147,
                  "height":109},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/花市一点通/u52.jpg"}},
{
          "id":"1506d394315f40db91460ec338dec8ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":30.5,
              "y":548},
            "size":{
              "width":131,
              "height":95},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcbe239011554d36b0ec861eb2eef712",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":30.5,
                  "y":548},
                "size":{
                  "width":131,
                  "height":95},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/花市一点通/u6.png"}},
{
          "id":"e2d7918fa8db4ff8a89984025edce1ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'幼圆 Bold', '幼圆'",
            "fontSize":"12px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":36,
              "y":626},
            "size":{
              "width":53,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfe10a2226004a56ad64d809df2a82ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'幼圆 Bold', '幼圆'",
                "fontSize":"12px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":36,
                  "y":626},
                "size":{
                  "width":53,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db119be2505e402fbb5ac596b7c54e84",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":198.5,
              "y":548},
            "size":{
              "width":131,
              "height":95},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19b9ba12924c43d7becb73422413a6d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":198.5,
                  "y":548},
                "size":{
                  "width":131,
                  "height":95},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/花市一点通/u6.png"}},
{
          "id":"a3c40b105cf94020ae851d765798129c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'幼圆 Bold', '幼圆'",
            "fontSize":"12px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":204,
              "y":626},
            "size":{
              "width":53,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27ffb30028a94f54800bd5f767f0d825",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'幼圆 Bold', '幼圆'",
                "fontSize":"12px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":204,
                  "y":626},
                "size":{
                  "width":53,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a1033564ec54a359d38568845cf29ba",
          "label":"启动画面",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"top",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"c68e59520c2542d1b3a54a76bba0bf68",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"1f2a3ba3107d44b58d00e067b555c031",
                  "label":"",
                  "parentDynamicPanel":"4a1033564ec54a359d38568845cf29ba",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFBD031A},
                    "size":{
                      "width":360,
                      "height":670},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "linePattern":"dashed"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5800dfd310b541d1b5b3e5edbdeeb9bd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4a1033564ec54a359d38568845cf29ba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFBD031A},
                        "size":{
                          "width":360,
                          "height":670},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "linePattern":"dashed"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/花市一点通/u63.png"}},
{
                  "id":"ebc909d0befd4b00b1066fa7a3072eae",
                  "label":"",
                  "parentDynamicPanel":"4a1033564ec54a359d38568845cf29ba",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":360,
                      "height":151}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9c4dd69df8c04321a67613dece284bdd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4a1033564ec54a359d38568845cf29ba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":360,
                          "height":151}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/花市一点通/u65.jpg"}},
{
                  "id":"0a9d70c40b3a4097a1af22dde29f619f",
                  "label":"",
                  "parentDynamicPanel":"4a1033564ec54a359d38568845cf29ba",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":40,
                      "y":161},
                    "size":{
                      "width":245,
                      "height":490}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"229d05d955ec4d0e83556d60e743853c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4a1033564ec54a359d38568845cf29ba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":40,
                          "y":161},
                        "size":{
                          "width":245,
                          "height":490}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/花市一点通/u67.png"}},
{
                  "id":"0ac5751df4d649ba9d4ccfe47783bb24",
                  "label":"",
                  "parentDynamicPanel":"4a1033564ec54a359d38568845cf29ba",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'幼圆 Regular', '幼圆'",
                    "fontSize":"11px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF333333},
                    "location":{
                      "x":310,
                      "y":640},
                    "size":{
                      "width":50,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"42f8721c287442afa45556f83ccc48c0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4a1033564ec54a359d38568845cf29ba",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'幼圆 Regular', '幼圆'",
                        "fontSize":"11px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF333333},
                        "location":{
                          "x":310,
                          "y":640},
                        "size":{
                          "width":50,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 启动画面 淡入淡出 500 ms",
                              "objectsToFades":[{
                                  "objectPath":["4a1033564ec54a359d38568845cf29ba"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "easing":"fade",
                                      "duration":500,
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/花市一点通/u69.png"}}]}]},
{
          "id":"6083526823ec4639b1c52f22542efc67",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":22,
              "y":20},
            "size":{
              "width":147,
              "height":110}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 西湖花市",
                      "target":{
                        "targetType":"page",
                        "url":"西湖花市.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"2270be8b707f4b0e9e0fcec39293305d",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":20},
            "size":{
              "width":147,
              "height":110}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 西湖花市",
                      "target":{
                        "targetType":"page",
                        "url":"西湖花市.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"53f8fa4f1e7541828f8288146b41d721",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":22,
              "y":149},
            "size":{
              "width":147,
              "height":110}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 西湖花市",
                      "target":{
                        "targetType":"page",
                        "url":"西湖花市.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"8d84949b814b4865bb1835cbef4c4910",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":148},
            "size":{
              "width":147,
              "height":110}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 西湖花市",
                      "target":{
                        "targetType":"page",
                        "url":"西湖花市.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"3ee8d62b250b4eb5bd35b00516b9f57a",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":22,
              "y":278},
            "size":{
              "width":147,
              "height":110}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 西湖花市",
                      "target":{
                        "targetType":"page",
                        "url":"西湖花市.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"80cc7a3b18504b8d965dbeb4bb5aa673",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":277},
            "size":{
              "width":147,
              "height":110}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 西湖花市",
                      "target":{
                        "targetType":"page",
                        "url":"西湖花市.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"0fc1af880e55408bae4f0c4d779e48b8",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":22,
              "y":410},
            "size":{
              "width":147,
              "height":110}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 西湖花市",
                      "target":{
                        "targetType":"page",
                        "url":"西湖花市.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"f6b11d40714b4857bf11f107d418215c",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":410},
            "size":{
              "width":147,
              "height":110}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 西湖花市",
                      "target":{
                        "targetType":"page",
                        "url":"西湖花市.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"8dbb095b101b4a37af86bc610165d822",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":22,
              "y":540},
            "size":{
              "width":147,
              "height":110}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 西湖花市",
                      "target":{
                        "targetType":"page",
                        "url":"西湖花市.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"b2d7e267298242adb927f3b2ae02dc26",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":540},
            "size":{
              "width":147,
              "height":110}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 西湖花市",
                      "target":{
                        "targetType":"page",
                        "url":"西湖花市.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "056fee0eb50a463bb8260f33e08798c4":{
      "scriptId":"u0"},
    "040eb4c086c748a7a112988194d5c499":{
      "scriptId":"u1"},
    "eaa99c89a8a64c3582492957da9a6a34":{
      "scriptId":"u2"},
    "3a9379ee03ca41f6a8bd18fc5d2e3ab2":{
      "scriptId":"u3"},
    "463395f535014d38ae4b41f9056df201":{
      "scriptId":"u4"},
    "ec2ab7c074674ceb82de26eddf6033db":{
      "scriptId":"u5"},
    "6bd9f42ac7554955ae59629633304fc7":{
      "scriptId":"u6"},
    "c6ea4747003a4adea4b91b3203a9de9d":{
      "scriptId":"u7"},
    "2a38bb876b3b4c5f9b5cf2199896a302":{
      "scriptId":"u8"},
    "6802caa209f244f7afae31a44586d2aa":{
      "scriptId":"u9"},
    "534c38e6c3684e9881bc9987519d8177":{
      "scriptId":"u10"},
    "be7bc044e9ba485faf89d12bbdace9cd":{
      "scriptId":"u11"},
    "1b2e02400c274897a35cd7e0c09e9bd1":{
      "scriptId":"u12"},
    "b27b2a0b0a8941b79ca5ddeb4708d8e8":{
      "scriptId":"u13"},
    "08be0606f21f4dfc8f7c1cf2b812663f":{
      "scriptId":"u14"},
    "44513f76fd074854bf2fee4bf5d52274":{
      "scriptId":"u15"},
    "7a3086c1ae894f25ba32a1743fae9872":{
      "scriptId":"u16"},
    "084171618f1c40e480a148469ea122bd":{
      "scriptId":"u17"},
    "21d2f267fdf643a4a761d7280c4009b1":{
      "scriptId":"u18"},
    "da18cc6f05ea4c8ca7b04307ad503529":{
      "scriptId":"u19"},
    "87cc9cacd5b5424487951a77764bade7":{
      "scriptId":"u20"},
    "81cdd2d4cd2a4c61a52541b58c39937e":{
      "scriptId":"u21"},
    "836838fdaaa44bfeb71beb664ea3ca72":{
      "scriptId":"u22"},
    "69ea2faf54374e30a4fc8caba44701b4":{
      "scriptId":"u23"},
    "46071d1dc25349a3984b662773d0f584":{
      "scriptId":"u24"},
    "569db57dfe2f40bf8577f3579c70c05a":{
      "scriptId":"u25"},
    "022498a4fd9a46dd880bc77886dae5d1":{
      "scriptId":"u26"},
    "b4ab49ee606a4c599afb1cca95ccd513":{
      "scriptId":"u27"},
    "04a131afd2ca4a78a42b4fcb03643521":{
      "scriptId":"u28"},
    "b04b61858c224c5c8015f9e5fdb959eb":{
      "scriptId":"u29"},
    "8a4f75e3ac084b88a58fd3550bf959df":{
      "scriptId":"u30"},
    "dfa4b0dce0fc44fda2abe8daad664002":{
      "scriptId":"u31"},
    "9836f1fdf21b4b0ebf184671f40eab2e":{
      "scriptId":"u32"},
    "7af20f05283442d79bc4c2d5fd2a34ef":{
      "scriptId":"u33"},
    "ab9b47655dc144e18a9e5fb4cc1ab107":{
      "scriptId":"u34"},
    "06fa125962ef4be08fa7edbf5abb05f1":{
      "scriptId":"u35"},
    "0c542348152643208308b6db33d8e530":{
      "scriptId":"u36"},
    "45f79a07b8aa4ff1a5078e730a45d593":{
      "scriptId":"u37"},
    "d28d0d858cb5471dab361e155747067d":{
      "scriptId":"u38"},
    "4d6c6cec28c04b93ba5bc735f428847a":{
      "scriptId":"u39"},
    "a2080f87b8d64ee28f106c8a20a9bfea":{
      "scriptId":"u40"},
    "60237bf28a3440fe9bed8e6851f4c458":{
      "scriptId":"u41"},
    "3a6e1318340b4d95a3a3e9f4c1e1dc2b":{
      "scriptId":"u42"},
    "87ac0a6b7a77486e87b05b2e94ffc1f5":{
      "scriptId":"u43"},
    "493b942a9a50422392c97b58961b37fe":{
      "scriptId":"u44"},
    "bdbb0dfed5814cb2b99f99d135d661b0":{
      "scriptId":"u45"},
    "07b90d0dc8c14611be43431922feefc9":{
      "scriptId":"u46"},
    "fc472651d65f4a6ca60f5ab21c887cab":{
      "scriptId":"u47"},
    "93b5d9f636714318ae054583d59f9c7d":{
      "scriptId":"u48"},
    "b5ce4804bf8d4858af9510c27b4d3456":{
      "scriptId":"u49"},
    "45307a7af6544025b34e192cb8559944":{
      "scriptId":"u50"},
    "c3a2ff857c684802a595d1995851f8ed":{
      "scriptId":"u51"},
    "9b4911a42bb04c12b767fb0ff0313450":{
      "scriptId":"u52"},
    "d80cd1625e294ec7b13b9487c25ca09e":{
      "scriptId":"u53"},
    "1506d394315f40db91460ec338dec8ff":{
      "scriptId":"u54"},
    "dcbe239011554d36b0ec861eb2eef712":{
      "scriptId":"u55"},
    "e2d7918fa8db4ff8a89984025edce1ad":{
      "scriptId":"u56"},
    "cfe10a2226004a56ad64d809df2a82ba":{
      "scriptId":"u57"},
    "db119be2505e402fbb5ac596b7c54e84":{
      "scriptId":"u58"},
    "19b9ba12924c43d7becb73422413a6d1":{
      "scriptId":"u59"},
    "a3c40b105cf94020ae851d765798129c":{
      "scriptId":"u60"},
    "27ffb30028a94f54800bd5f767f0d825":{
      "scriptId":"u61"},
    "4a1033564ec54a359d38568845cf29ba":{
      "scriptId":"u62"},
    "1f2a3ba3107d44b58d00e067b555c031":{
      "scriptId":"u63"},
    "5800dfd310b541d1b5b3e5edbdeeb9bd":{
      "scriptId":"u64"},
    "ebc909d0befd4b00b1066fa7a3072eae":{
      "scriptId":"u65"},
    "9c4dd69df8c04321a67613dece284bdd":{
      "scriptId":"u66"},
    "0a9d70c40b3a4097a1af22dde29f619f":{
      "scriptId":"u67"},
    "229d05d955ec4d0e83556d60e743853c":{
      "scriptId":"u68"},
    "0ac5751df4d649ba9d4ccfe47783bb24":{
      "scriptId":"u69"},
    "42f8721c287442afa45556f83ccc48c0":{
      "scriptId":"u70"},
    "6083526823ec4639b1c52f22542efc67":{
      "scriptId":"u71"},
    "2270be8b707f4b0e9e0fcec39293305d":{
      "scriptId":"u72"},
    "53f8fa4f1e7541828f8288146b41d721":{
      "scriptId":"u73"},
    "8d84949b814b4865bb1835cbef4c4910":{
      "scriptId":"u74"},
    "3ee8d62b250b4eb5bd35b00516b9f57a":{
      "scriptId":"u75"},
    "80cc7a3b18504b8d965dbeb4bb5aa673":{
      "scriptId":"u76"},
    "0fc1af880e55408bae4f0c4d779e48b8":{
      "scriptId":"u77"},
    "f6b11d40714b4857bf11f107d418215c":{
      "scriptId":"u78"},
    "8dbb095b101b4a37af86bc610165d822":{
      "scriptId":"u79"},
    "b2d7e267298242adb927f3b2ae02dc26":{
      "scriptId":"u80"}}});