$axure.loadCurrentPage({
  "url":"醉美花店.html",
  "generationDate":new Date(1516111894537.28),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"67ce4daa134f44718bf695c0e040370d",
    "type":"Axure:Page",
    "name":"醉美花店",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fefaf464029e4350a6656858413a5cf2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":750},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be5f08abd7fe4f65aca1606136d3026d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":750},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/醉美花店/u0.png"}},
{
          "id":"782e7ba86a0b470bbb1ab5af3516bc77",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":5,
              "y":58},
            "size":{
              "width":180,
              "height":180},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c023c454d1cf445ab217f8f6c53a953d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":5,
                  "y":58},
                "size":{
                  "width":180,
                  "height":180},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/醉美花店/u2.png"}},
{
          "id":"a75adc8dfca84feebbd932e665c2db54",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":58},
            "size":{
              "width":79,
              "height":84},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c926020953474493891d0061284eb70a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":58},
                "size":{
                  "width":79,
                  "height":84},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/醉美花店/u4.png"}},
{
          "id":"c36ea485212b4cb0bc5c73832b0beb37",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":154},
            "size":{
              "width":80,
              "height":84},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05afa65405f145fba6e9bbdf844b07cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":154},
                "size":{
                  "width":80,
                  "height":84},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/醉美花店/u6.png"}},
{
          "id":"d547d16f6363427f8568b9f97c960e2c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":275,
              "y":58},
            "size":{
              "width":79,
              "height":84},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3304e2ae3ef74ba6ac1190192f29f14b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":275,
                  "y":58},
                "size":{
                  "width":79,
                  "height":84},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/醉美花店/u8.png"}},
{
          "id":"901f4ca2df93474e958bdfb934450aa6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":275,
              "y":154},
            "size":{
              "width":80,
              "height":84},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4d76e3d7129406a8fe47e220818d190",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":275,
                  "y":154},
                "size":{
                  "width":80,
                  "height":84},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/醉美花店/u10.png"}},
{
          "id":"696a0ef0c9c942ab95c8d36ce7e08eb3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":403},
            "size":{
              "width":30,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1739f6a123d94b5294f7b63573745fc4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":9,
                  "y":403},
                "size":{
                  "width":30,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/西湖花市/u101.png"}},
{
          "id":"b68c460a2c194e36961daff45e6f73a5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":365},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc62ff76c4b6438ba7897173c2ff124a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":14,
                  "y":365},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/醉美花店/u14.png"}},
{
          "id":"6807e242cce3490cb2ca02ee12f20bbd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":247.5},
            "size":{
              "width":30,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75d1c64d9fd7471ea5be267c58296234",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":14,
                  "y":247.5},
                "size":{
                  "width":30,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/醉美花店/u16.png"}},
{
          "id":"3c75b811e6024035a75ebd3e7e461c16",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":144,
              "y":11},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c432c2699314c9b97c821cbae134e61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":144,
                  "y":11},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"334f530283ff43d0aa040bf8cdb92196",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":49,
              "y":410},
            "size":{
              "width":106,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5ece35c4f384c7ab249d556b61064f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":49,
                  "y":410},
                "size":{
                  "width":106,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc4a4d85f0174791aa9a6dd072d09b01",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":369},
            "size":{
              "width":54,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ccbf29579484a4e909f44f7cc0ab509",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":369},
                "size":{
                  "width":54,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"925acba676c94739b41084562f3cd8fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":54,
              "y":256},
            "size":{
              "width":266,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56a7490c12bb4ffbafb09554b6f55364",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":54,
                  "y":256},
                "size":{
                  "width":266,
                  "height":96}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4f655db2353245248de0b81110b492f2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":148,
              "y":596},
            "size":{
              "width":64,
              "height":64},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"567a27006f49469fac71057f39ac1130",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":148,
                  "y":596},
                "size":{
                  "width":64,
                  "height":64},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/醉美花店/u26.png"}},
{
          "id":"6e694fb6257f4049984a116c1ebbb4ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":154,
              "y":668},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cee4236fecbb4211b43c6816e294e301",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":154,
                  "y":668},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"be01670d0be7469db4ca860b108e675c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":686},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"257f01613dce47fdb2b6e269a7d8c4bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":159,
                  "y":686},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c3888914661049b6aa93e32bdf0ed15a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":151,
              "y":600},
            "size":{
              "width":58,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a27995b97734d2faa379e60c55bed10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":151,
                  "y":600},
                "size":{
                  "width":58,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/醉美花店/u32.png"}},
{
          "id":"16a023607a4f458ca3637d9c12058cb4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":19,
              "y":442},
            "size":{
              "width":307,
              "height":122}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5da22da6bd5c4aaa82d6a907059e605c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":19,
                  "y":442},
                "size":{
                  "width":307,
                  "height":122}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/醉美花店/u34.png"}},
{
          "id":"ba7310f6210542b1b6eee50b546fc90a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":44,
              "height":44},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3864031dbe034044afa2032f47579bf9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":44,
                  "height":44},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/醉美花店/u36.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "fefaf464029e4350a6656858413a5cf2":{
      "scriptId":"u0"},
    "be5f08abd7fe4f65aca1606136d3026d":{
      "scriptId":"u1"},
    "782e7ba86a0b470bbb1ab5af3516bc77":{
      "scriptId":"u2"},
    "c023c454d1cf445ab217f8f6c53a953d":{
      "scriptId":"u3"},
    "a75adc8dfca84feebbd932e665c2db54":{
      "scriptId":"u4"},
    "c926020953474493891d0061284eb70a":{
      "scriptId":"u5"},
    "c36ea485212b4cb0bc5c73832b0beb37":{
      "scriptId":"u6"},
    "05afa65405f145fba6e9bbdf844b07cd":{
      "scriptId":"u7"},
    "d547d16f6363427f8568b9f97c960e2c":{
      "scriptId":"u8"},
    "3304e2ae3ef74ba6ac1190192f29f14b":{
      "scriptId":"u9"},
    "901f4ca2df93474e958bdfb934450aa6":{
      "scriptId":"u10"},
    "b4d76e3d7129406a8fe47e220818d190":{
      "scriptId":"u11"},
    "696a0ef0c9c942ab95c8d36ce7e08eb3":{
      "scriptId":"u12"},
    "1739f6a123d94b5294f7b63573745fc4":{
      "scriptId":"u13"},
    "b68c460a2c194e36961daff45e6f73a5":{
      "scriptId":"u14"},
    "dc62ff76c4b6438ba7897173c2ff124a":{
      "scriptId":"u15"},
    "6807e242cce3490cb2ca02ee12f20bbd":{
      "scriptId":"u16"},
    "75d1c64d9fd7471ea5be267c58296234":{
      "scriptId":"u17"},
    "3c75b811e6024035a75ebd3e7e461c16":{
      "scriptId":"u18"},
    "8c432c2699314c9b97c821cbae134e61":{
      "scriptId":"u19"},
    "334f530283ff43d0aa040bf8cdb92196":{
      "scriptId":"u20"},
    "c5ece35c4f384c7ab249d556b61064f3":{
      "scriptId":"u21"},
    "cc4a4d85f0174791aa9a6dd072d09b01":{
      "scriptId":"u22"},
    "5ccbf29579484a4e909f44f7cc0ab509":{
      "scriptId":"u23"},
    "925acba676c94739b41084562f3cd8fb":{
      "scriptId":"u24"},
    "56a7490c12bb4ffbafb09554b6f55364":{
      "scriptId":"u25"},
    "4f655db2353245248de0b81110b492f2":{
      "scriptId":"u26"},
    "567a27006f49469fac71057f39ac1130":{
      "scriptId":"u27"},
    "6e694fb6257f4049984a116c1ebbb4ee":{
      "scriptId":"u28"},
    "cee4236fecbb4211b43c6816e294e301":{
      "scriptId":"u29"},
    "be01670d0be7469db4ca860b108e675c":{
      "scriptId":"u30"},
    "257f01613dce47fdb2b6e269a7d8c4bb":{
      "scriptId":"u31"},
    "c3888914661049b6aa93e32bdf0ed15a":{
      "scriptId":"u32"},
    "0a27995b97734d2faa379e60c55bed10":{
      "scriptId":"u33"},
    "16a023607a4f458ca3637d9c12058cb4":{
      "scriptId":"u34"},
    "5da22da6bd5c4aaa82d6a907059e605c":{
      "scriptId":"u35"},
    "ba7310f6210542b1b6eee50b546fc90a":{
      "scriptId":"u36"},
    "3864031dbe034044afa2032f47579bf9":{
      "scriptId":"u37"}}});